name: first-project

services:
  database:
    image: postgres:17.5
    restart: unless-stopped
    ports:
      - "10350:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: