[versions]
# Core frameworks / libraries
spring-boot = "3.2.2"
springdoc-openapi = "2.1.0"
mapstruct = "1.6.3"
liquibase = "4.30.0"
jackson = "2.18.2"
aspectj = "1.9.25"
lombok = "1.18.42"
postgresql = "42.7.8"

# Testing
testcontainers = "2.0.2"
testcontainers-postgresql = "1.21.3"
assertj = "4.0.0-M1"
mockito = "5.20.0"
jsonassert = "1.5.3"
json-path = "2.10.0"
hamcrest = "3.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }

[libraries]
# Spring
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-log4j2 = { module = "org.springframework.boot:spring-boot-starter-log4j2" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
springdoc-openapi-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }

# Persistence
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }

# Utility
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
aspectj-rt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Testing
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "json-path" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# Test containers
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers-postgresql" }

[bundles]
spring-web = ["spring-boot-starter-web", "springdoc-openapi-webmvc-ui", "jackson-datatype-jsr310"]
validation = ["spring-boot-starter-validation"]
testing = ["spring-boot-starter-test", "assertj-core", "mockito-core", "jsonassert", "json-path", "hamcrest", "junit-platform-launcher"]
testcontainers-all = ["testcontainers", "testcontainers-junit-jupiter", "testcontainers-postgresql"]
aspectj-all = ["aspectj-rt", "aspectj-weaver"]
