spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: ${database.connect.application_scheme}
    liquibase-schema: ${database.migration.liquibase.scheme}

  datasource:
    url: ${database.connect.url}
    username: ${database.connect.user}
    password: ${database.connect.password}